version: "3.6"
services:
  app:
    container_name: taxi-server
    hostname: taxi-server
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
      BASIC_ENV: prod
    ports:
      - 1323:1323
